/* config.h */


#pragma once


#define MASTER_RIGHT


#define SERIAL_DEBUG
#define SERIAL_PIO_USE_PIO0
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_SPEED  1000000


#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT  1000


#define SPI_DRIVER      SPID1
#define SPI_SCK_PIN     GP26
#define SPI_MISO_PIN    GP24
#define SPI_MOSI_PIN    GP27
#define PMW33XX_CS_PIN  GP25
#define PMW33XX_CPI     600

#define POINTING_DEVICE_TASK_THROTTLE_MS  4

#define WHEEL_EXTENDED_REPORT
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER  15


#define NO_ALT_REPEAT_KEY


#define VOW_EXTRA_LAYERS  LYR_MED
