/* config.h */


#pragma once


#define WS2812_PIO_USE_PIO1

#define USB_VBUS_PIN  GP27


#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED      GP17
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT  1000


#define SPI_DRIVER      SPID0
#define SPI_SCK_PIN     GP22
#define SPI_MISO_PIN    GP20
#define SPI_MOSI_PIN    GP23
#define PMW33XX_CS_PIN  GP21
#define PMW33XX_CPI     600

#define POINTING_DEVICE_INVERT_Y
#define ROTATIONAL_TRANSFORM_ANGLE  -15

#define POINTING_DEVICE_TASK_THROTTLE_MS  4

#define WHEEL_EXTENDED_REPORT
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER  15
